---
driver:
  name: docker
  binary: docker
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: debian-7
  - name: debian-8

suites:
  - name: default
    run_list:
      - recipe[python]
      - recipe[pentester]
    attributes:
      pentester:
        sn1per:
          packages: []
  - name: gitrob
    run_list:
      - recipe[pentester::gitrob]
