AllCops:
  Include:
    - metadata.rb
    - '**/Gemfile'
    - '**/Guardfile'
    - attributes/**/*
    - definitions/**/*
    - libraries/**/*
    - providers/**/*
    - recipes/**/*
    - resources/**/*
    - spec/**/*
    - test/**/*
  Exclude:
    - cookbooks/**/*
    - vendor/**/*

LineLength:
  Exclude:
    - spec/*
